name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: autoreconf -fi && ./configure && make
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: autoreconf -fi
      - run: ./configure
      - run: make check
      - run: contrib/run_tests.sh
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: for file in $(find -name *.[c,h,hpp]); do clang-format --dry-run --Werror $file; done

