name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make
      run: autoreconf -fi && ./configure && make

    - name: make test
      run: autoreconf -fi && ./configure && make check && ./test_flat_file && ./test_forest
    
    - name: linting
      run: for file in $(find -name *.[c,h,hpp]); do clang-format --dry-run --Werror $file; done
